training_dataset: "/home/hpsauce/ROSCO/ZMQ_Prediction_ROSCO/DOLPHINN/data/TEST_DATA_COMMA.csv"
dof:
  - "PtfmTDX"
  - "PtfmTDY"
  - "PtfmTDZ"
  - "PtfmRDX"
  - "PtfmRDY"
  - "PtfmRDZ"
  - "FA_Acc"
unit:
  - "[m]"
  - "[m]"
  - "[deg]"
  - "[kN]"
  - "[kN]"
  - "[kN]"
  - "[m-s2]"
conversion:
  - 1
  - 1
  - 1
  - 0.001
  - 0.001
  - 0.001
  - 1
time_horizon: 20
nm: 0.588482
hidden_layer: 1
neuron_number: 96
epochs: 60
batch_time: 53
timestep: 1.0
lr: 0.001
dropout: 0.0
train_ratio: 0.50
valid_ratio: 0.25
wind_prediction: False
wave_prediction: True