batch_time: 53
conversion:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
dof:
- PtfmTDX
- PtfmTDZ
- PtfmTDY
- PtfmRDX
- PtfmRDY
- PtfmRDZ
- BlPitchCMeas
- RotSpeed
dropout: 0.2
epochs: 8
hidden_layer: 1
lr: 1.6e-05
neuron_number: 64
nm: 0.588482
time_horizon: 20
timestep: 1.0
train_ratio: 0.7
training_dataset: /Users/fredrikfleslandselheim/ROSCO/Digital_Twin_ZMQ/Blade_Pitch_Prediction/DOLPHINN/training_data/TrainingData_Hs2_75_Tp6_14400sec.csv
unit:
- '[m]'
- '[m]'
- '[m]'
- '[deg]'
- '[deg]'
- '[deg]'
- '[deg]'
- '[deg/s]'
valid_ratio: 0.15
wave_prediction: true
wind_prediction: false
