training_dataset: "data/windwave.csv"
dof:
  - "Surge"
  - "Heave"
  - "Pitch"
  - "rotorTorque"
  - "genSpeed"
  - "leg3MooringForce"
  - "accelNacelleAx"
  - "towerBotMy"
unit:
  - "[m]"
  - "[m]"
  - "[deg]"
  - "[kN.m]"
  - "[rad/s]"
  - "[kN]"
  - "[m/s^2]"
  - "[kN.m]"
conversion:
  - 1
  - 1
  - 1
  - 0.001
  - 1
  - 0.001
  - 1
  - 0.001
time_horizon: 20
nm: 0.39
hidden_layer: 1
neuron_number: 100
epochs: 80
batch_time: 47
timestep: 1.0
lr: 0.001
dropout: 0.0
train_ratio: 0.50
valid_ratio: 0.25
wind_prediction: False
wave_prediction: True